# Generated by Django 4.1.7 on 2023-02-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='info',
            field=models.TextField(max_length=150),
        ),
    ]
